{
  "uid" : "9125d7c654cc7c4f",
  "name" : "test_buy_empty_basket",
  "fullName" : "test.test_main_page.TestMainPage#test_buy_empty_basket",
  "historyId" : "d6b5786680b38868ad821954821da58b",
  "time" : {
    "start" : 1650552892728,
    "stop" : 1650552892728,
    "duration" : 0
  },
  "description" : "\n        Попытка купить, если корзина пуста.\n        ",
  "descriptionHtml" : "<pre><code>    Попытка купить, если корзина пуста.\n</code></pre>\n",
  "status" : "skipped",
  "statusMessage" : "Skipped: missing notification",
  "statusTrace" : "('/home/runner/work/Test_with_a_team/Test_with_a_team/test/test_main_page.py', 22, 'Skipped: missing notification')",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1650552881559,
      "stop" : 1650552881577,
      "duration" : 18
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "app",
    "time" : {
      "start" : 1650552893185,
      "stop" : 1650552893897,
      "duration" : 712
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b425955ad3 <unknown>\n#1 0x55b4256b5568 <unknown>\n#2 0x55b4256d8b37 <unknown>\n#3 0x55b4256d423a <unknown>\n#4 0x55b42570f2ba <unknown>\n#5 0x55b4257094e3 <unknown>\n#6 0x55b4256ded1a <unknown>\n#7 0x55b4256dfe75 <unknown>\n#8 0x55b425983efd <unknown>\n#9 0x55b42599d19b <unknown>\n#10 0x55b425985c65 <unknown>\n#11 0x55b42599dec8 <unknown>\n#12 0x55b425979360 <unknown>\n#13 0x55b4259b9a68 <unknown>\n#14 0x55b4259b9be8 <unknown>\n#15 0x55b4259d37fd <unknown>\n#16 0x7ff479a12609 <unknown>\n\n",
    "statusTrace" : "  File \"/home/runner/.local/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/Test_with_a_team/Test_with_a_team/conftest.py\", line 38, in app\n    driver = webdriver.Chrome(ChromeDriverManager().install(),\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 93, in __init__\n    RemoteWebDriver.__init__(\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 360, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "register_user",
    "time" : {
      "start" : 1650552892731,
      "stop" : 1650552893185,
      "duration" : 454
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.skip(reason='missing notification')"
  }, {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "test_main_page"
  }, {
    "name" : "subSuite",
    "value" : "TestMainPage"
  }, {
    "name" : "host",
    "value" : "fv-az397-282"
  }, {
    "name" : "thread",
    "value" : "2228-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_main_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.skip(reason='missing notification')" ]
  },
  "source" : "9125d7c654cc7c4f.json",
  "parameterValues" : [ ]
}